name: Issue Reply

on:
  issues:
    types: [labeled]

jobs:
  issue-reply:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Need Reproduce
        if: github.event.label.name == 'Need Reproduce'
        uses: actions-cool/issues-helper@v3
        with:
          actions: create-comment
          issue-number: ${{ github.event.issue.number }}
          body: |
            你好 @${{ github.event.issue.user.login }}, 我们需要你提供一个最小重现实例以便于我们帮你排查问题。你可以提供一个基于 Vite 模板项目的 GitHub 仓库链接（`nutui-uniapp/nutui-uniapp-demo`），也可以通过 [StackBlitz](https://stackblitz.com/~/github.com/nutui-uniapp/nutui-uniapp-demo) 创建一个在线实例（`nutui-uniapp`）。请确保选择准确的版本。
